(function(){
 const db=()=>window.connectWorldSupabase;
 const ok=()=>!!db();
 async function user(){if(!ok())return null;const {data}=await db().auth.getUser();return data.user||null}
 async function profile(id){const {data,error}=await db().from("profiles").select("*").eq("id",id).single();if(error)throw error;return data}
 async function notify(userId,type,message,entityId=null){const u=await user();if(!u||!userId||u.id===userId)return;const {error}=await db().from("notifications").insert({user_id:userId,actor_id:u.id,type,message,entity_id:entityId});if(error)console.warn(error)}
 async function signUp(email,password,meta){const {data,error}=await db().auth.signUp({email,password,options:{data:meta}});if(error)throw error;return data}
 async function signIn(email,password){const {data,error}=await db().auth.signInWithPassword({email,password});if(error)throw error;return data}
 async function signOut(){const {error}=await db().auth.signOut();if(error)throw error}
 async function resetPassword(email){const {error}=await db().auth.resetPasswordForEmail(email,{redirectTo:location.href});if(error)throw error}
 async function updateProfile(values){const u=await user();if(!u)throw Error("Please log in.");const {data,error}=await db().from("profiles").update(values).eq("id",u.id).select().single();if(error)throw error;return data}
 async function listPosts(){const {data,error}=await db().from("posts").select("*,profiles(id,username,full_name,avatar_url,country),likes(user_id),comments(id,content,created_at,user_id,profiles(username,full_name,avatar_url))").order("created_at",{ascending:false}).limit(30);if(error)throw error;return data||[]}
 async function createPost(content,imageUrl){const u=await user();if(!u)throw Error("Please log in.");const {data,error}=await db().from("posts").insert({user_id:u.id,content:content||"",image_url:imageUrl||null}).select().single();if(error)throw error;return data}
 async function postOwner(postId){const {data,error}=await db().from("posts").select("user_id").eq("id",postId).single();if(error)throw error;return data.user_id}
 async function toggleLike(postId,liked){const u=await user();if(!u)throw Error("Please log in.");if(liked){const {error}=await db().from("likes").delete().eq("post_id",postId).eq("user_id",u.id);if(error)throw error;return false}else{const {error}=await db().from("likes").insert({post_id:postId,user_id:u.id});if(error)throw error;await notify(await postOwner(postId),"like","liked your post",postId);return true}}
 async function addComment(postId,content){const u=await user();if(!u)throw Error("Please log in.");const {data,error}=await db().from("comments").insert({post_id:postId,user_id:u.id,content}).select().single();if(error)throw error;await notify(await postOwner(postId),"comment","commented on your post",postId);return data}
 async function discover(filters={}){let q=db().from("profiles").select("*").order("created_at",{ascending:false}).limit(100);if(filters.country)q=q.eq("country",filters.country);if(filters.interest)q=q.contains("interests",[filters.interest]);const {data,error}=await q;if(error)throw error;return data||[]}
 async function friendshipWith(otherId){const u=await user();if(!u)return null;const {data,error}=await db().from("friendships").select("*").or(`and(requester_id.eq.${u.id},addressee_id.eq.${otherId}),and(requester_id.eq.${otherId},addressee_id.eq.${u.id})`);if(error)throw error;return data?.[0]||null}
 async function sendFriendRequest(id){const u=await user();if(!u)throw Error("Please log in.");const existing=await friendshipWith(id);if(existing)return existing;const {data,error}=await db().from("friendships").insert({requester_id:u.id,addressee_id:id}).select().single();if(error)throw error;await notify(id,"friend_request","sent you a friend request",data.id);return data}
 async function respondFriendRequest(id,status){const u=await user();if(!u)throw Error("Please log in.");const {data,error}=await db().from("friendships").update({status}).eq("id",id).eq("addressee_id",u.id).select().single();if(error)throw error;if(status==="accepted")await notify(data.requester_id,"friend_accepted","accepted your friend request",id);return data}
 async function removeFriend(otherId){const u=await user();if(!u)throw Error("Please log in.");const {error}=await db().from("friendships").delete().or(`and(requester_id.eq.${u.id},addressee_id.eq.${otherId}),and(requester_id.eq.${otherId},addressee_id.eq.${u.id})`);if(error)throw error}
 async function friends(){const u=await user();if(!u)return [];const {data,error}=await db().from("friendships").select("*").eq("status","accepted").or(`requester_id.eq.${u.id},addressee_id.eq.${u.id}`);if(error)throw error;const ids=(data||[]).map(x=>x.requester_id===u.id?x.addressee_id:x.requester_id);if(!ids.length)return [];const {data:ps,error:e}=await db().from("profiles").select("*").in("id",ids);if(e)throw e;return ps||[]}
 async function requests(){const u=await user();if(!u)return [];const {data,error}=await db().from("friendships").select("*,profiles!friendships_requester_id_fkey(id,username,full_name,avatar_url,country)").eq("addressee_id",u.id).eq("status","pending");if(error)throw error;return data||[]}
 async function notifications(){const u=await user();if(!u)return [];const {data,error}=await db().from("notifications").select("*,profiles!notifications_actor_id_fkey(full_name,avatar_url)").eq("user_id",u.id).order("created_at",{ascending:false}).limit(30);if(error)throw error;return data||[]}
 async function markNotificationsRead(){const u=await user();if(!u)return;await db().from("notifications").update({read:true}).eq("user_id",u.id).eq("read",false)}
 async function conversations(otherId){const u=await user();if(!u)throw Error("Please log in.");const {data,error}=await db().from("messages").select("*").or(`and(sender_id.eq.${u.id},receiver_id.eq.${otherId}),and(sender_id.eq.${otherId},receiver_id.eq.${u.id})`).order("created_at",{ascending:true}).limit(100);if(error)throw error;return data||[]}
 async function sendMessage(receiverId,content){const u=await user();if(!u)throw Error("Please log in.");const {data,error}=await db().from("messages").insert({sender_id:u.id,receiver_id:receiverId,content}).select().single();if(error)throw error;await notify(receiverId,"message","sent you a message",data.id);return data}
 async function uploadImage(file,folder="posts"){const u=await user();if(!u)throw Error("Please log in.");if(!file)return null;const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-z0-9]/gi,"");const path=`${folder}/${u.id}-${Date.now()}.${ext}`;const {error}=await db().storage.from("connectworld-media").upload(path,file,{upsert:true,contentType:file.type});if(error)throw error;return db().storage.from("connectworld-media").getPublicUrl(path).data.publicUrl}
 function subscribe(table,callback,filter){if(!ok())return null;const channel=db().channel(`connectworld-${table}-${Date.now()}`).on("postgres_changes",{event:"*",schema:"public",table,...(filter?{filter}:{})},callback);channel.subscribe();return channel}
 window.ConnectWorld={configured:ok,user,profile,signUp,signIn,signOut,resetPassword,updateProfile,listPosts,createPost,toggleLike,addComment,discover,friendshipWith,sendFriendRequest,respondFriendRequest,removeFriend,friends,requests,notifications,markNotificationsRead,conversations,sendMessage,uploadImage,subscribe};
})();